### PR TITLE
Please review QuickSight update

### PR DESCRIPTION
**Pull request by ahmedhany**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sinanerdem** [comment]
For 6.3, I see the region dropdown differently. Is it because it is an Isengard account? Screenshot attached.

Screenshot 2021-07-19 at 17 59 04

**Comment by sinanerdem** [comment]
6.4 data edit page is different in terms of visuals for me. 

There is no arrow icon next to any field. Instead there are three dots.

Screenshot 2021-07-19 at 18 05 06

**Comment by sinanerdem** [comment]
6.5 -> The first lists start from 2 instead of 1. And step 4 and 5 are inside the paragraph.

Screenshot 2021-07-19 at 18 07 29

**Comment by sinanerdem** [comment]
The icons on the top right for the chart is different for me.

Screenshot 2021-07-19 at 18 10 30

**Comment by AhmedsZamzam** [comment]
Approved

**Review by AhmedsZamzam — APPROVED** [review]
Approved

**Pull request merged**
